version: "3.9"

services:
  api:
    container_name: vehicles_commerce_api
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "yarn prisma migrate dev --name init && yarn dev"
    volumes:
      - .:/vehicles_commerce_api

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
